import matplotlib.pyplot as plt
import os
import pandas as pd
import numpy as np
from collections import defaultdict
### dataset preparation
# get the path of the given data
path = os.path.dirname(os.path.abspath(__file__)) + '/result1.csv'
result = pd.read_csv(path)
plt.title("Comparison of R2 and RMSE when using different movement ways (Mode type: LR)")
plt.ylabel("R2")
plt.xlabel("window size / movement way")
plt.grid(color='grey', axis = 'y', linestyle=':', linewidth=1)
bins = np.arange(4)
plt.ylim(0,1.0)
plt.xticks(bins,('20/1','20/7','20/10','20/20'))
plt.plot(bins,result['R2'][:4],label = 'R2 for validation dataset',color='steelblue')
plt.plot(bins,result['RMSE'][:4],label = 'RMSE for validation dataset',color='sandybrown')
plt.plot(bins,result['R22'][:4],label = 'R2 for test dataset',color='mediumvioletred')
plt.plot(bins,result['RMSE2'][:4],label = 'RMSE for test dataset',color='seagreen')
plt.legend()
plt.show()


plt.title("Comparison of R2 and RMSE when using different algorithms (Mode type: LR")
plt.ylabel("R2")
plt.xlabel("Algorithm")
plt.grid(color='grey', axis = 'y', linestyle=':', linewidth=1)
bins = np.arange(7)
plt.ylim(0,1.0)
plt.xticks(bins,('Algorithm0','Algorithm1','Algorithm2','Algorithm3','Algorithm4','Algorithm5','Algorithm6'))
plt.plot(bins,result['R2'][5:12],label = 'R2 for validation dataset',color='steelblue')
plt.plot(bins,result['RMSE'][5:12],label = 'RMSE for validation dataset',color='sandybrown')
plt.plot(bins,result['R22'][5:12],label = 'R2 for test dataset',color='mediumvioletred')
plt.plot(bins,result['RMSE2'][5:12],label = 'RMSE for test dataset',color='seagreen')
plt.legend()
plt.show()

# plt.title("Comparison of R2 when using different movement ways (Mode type: LOR)")
# plt.ylabel("R2")
# plt.xlabel("window size / movement way")
# plt.grid(color='grey', axis = 'y', linestyle=':', linewidth=1)
# bins = np.arange(4)
# plt.ylim(0,1.0)
# plt.xticks(bins,('20/1','20/7','20/10','20/20'))
# plt.plot(bins,result['R2'][:4],label = 'R2 for validation dataset',color='steelblue')
# plt.plot(bins,result['R22'][:4],label = 'R2 for test dataset',color='mediumvioletred')
# plt.legend()
# plt.show()
#
# plt.title("Comparison of RMSE when using different movement ways (Mode type: LOR)")
# plt.ylabel("R2")
# plt.xlabel("window size / movement way")
# plt.grid(color='grey', axis = 'y', linestyle=':', linewidth=1)
# bins = np.arange(4)
# plt.xticks(bins,('20/1','20/7','20/10','20/20'))
# plt.plot(bins,result['RMSE'][:4],label = 'RMSE for validation dataset',color='sandybrown')
# plt.plot(bins,result['RMSE2'][:4],label = 'RMSE for test dataset',color='seagreen')
# plt.legend()
# plt.show()
#
# plt.title("Comparison of R2 when using different algorithms (Mode type: LOR")
# plt.ylabel("R2")
# plt.xlabel("Algorithm")
# plt.grid(color='grey', axis = 'y', linestyle=':', linewidth=1)
# bins = np.arange(7)
# plt.ylim(0,1.0)
# plt.xticks(bins,('Algorithm0','Algorithm1','Algorithm2','Algorithm3','Algorithm4','Algorithm5','Algorithm6'))
# plt.plot(bins,result['R2'][5:12],label = 'R2 for validation dataset',color='steelblue')
# plt.plot(bins,result['R22'][5:12],label = 'R2 for test dataset',color='mediumvioletred')
# plt.legend()
# plt.show()
#
# plt.title("Comparison of RMSE when using different algorithms (Mode type: LOR")
# plt.ylabel("R2")
# plt.xlabel("Algorithm")
# plt.grid(color='grey', axis = 'y', linestyle=':', linewidth=1)
# bins = np.arange(7)
# plt.xticks(bins,('Algorithm0','Algorithm1','Algorithm2','Algorithm3','Algorithm4','Algorithm5','Algorithm6'))
# plt.plot(bins,result['RMSE'][5:12],label = 'RMSE for validation dataset',color='sandybrown')
# plt.plot(bins,result['RMSE2'][5:12],label = 'RMSE for test dataset',color='seagreen')
# plt.legend()
# plt.show()
